#pragma once

#ifdef __cplusplus
#include <cstdint>
#else
#include <stdint.h>
#endif

#define ANTIVIRUS_REALTIME_PROTOCOL_VERSION 1u
#define ANTIVIRUS_REALTIME_PORT_NAME L"\\AntiVirusRealtimePort"
#define ANTIVIRUS_REALTIME_CORRELATION_CAPACITY 64u
#define ANTIVIRUS_REALTIME_PATH_CAPACITY 520u
#define ANTIVIRUS_REALTIME_IMAGE_CAPACITY 260u
#define ANTIVIRUS_REALTIME_COMMAND_LINE_CAPACITY 520u
#define ANTIVIRUS_REALTIME_USER_SID_CAPACITY 128u
#define ANTIVIRUS_REALTIME_REASON_CODE_CAPACITY 64u
#define ANTIVIRUS_REALTIME_REASON_MESSAGE_CAPACITY 256u
#define ANTIVIRUS_REALTIME_ATTACK_ID_CAPACITY 32u

#ifdef __cplusplus
extern "C" {
#endif

#pragma pack(push, 8)

typedef enum ANTIVIRUS_REALTIME_FILE_OPERATION {
  ANTIVIRUS_REALTIME_FILE_OPERATION_CREATE = 1,
  ANTIVIRUS_REALTIME_FILE_OPERATION_OPEN = 2,
  ANTIVIRUS_REALTIME_FILE_OPERATION_WRITE = 3,
  ANTIVIRUS_REALTIME_FILE_OPERATION_EXECUTE = 4,
  ANTIVIRUS_REALTIME_FILE_OPERATION_RENAME = 5,
  ANTIVIRUS_REALTIME_FILE_OPERATION_SECTION_MAP = 6
} ANTIVIRUS_REALTIME_FILE_OPERATION;

typedef enum ANTIVIRUS_REALTIME_RESPONSE_ACTION {
  ANTIVIRUS_REALTIME_RESPONSE_ACTION_ALLOW = 1,
  ANTIVIRUS_REALTIME_RESPONSE_ACTION_BLOCK = 2
} ANTIVIRUS_REALTIME_RESPONSE_ACTION;

typedef enum ANTIVIRUS_REALTIME_RESPONSE_DISPOSITION {
  ANTIVIRUS_REALTIME_RESPONSE_DISPOSITION_CLEAN = 1,
  ANTIVIRUS_REALTIME_RESPONSE_DISPOSITION_SUSPICIOUS = 2,
  ANTIVIRUS_REALTIME_RESPONSE_DISPOSITION_MALICIOUS = 3
} ANTIVIRUS_REALTIME_RESPONSE_DISPOSITION;

#define ANTIVIRUS_REALTIME_REQUEST_FLAG_EXECUTE_INTENT 0x00000001u
#define ANTIVIRUS_REALTIME_REQUEST_FLAG_WRITE_INTENT 0x00000002u
#define ANTIVIRUS_REALTIME_REQUEST_FLAG_RENAME_INTENT 0x00000004u
#define ANTIVIRUS_REALTIME_REQUEST_FLAG_REMOTE_VOLUME 0x00000008u
#define ANTIVIRUS_REALTIME_REQUEST_FLAG_REMOVABLE_VOLUME 0x00000010u
#define ANTIVIRUS_REALTIME_REQUEST_FLAG_CLOUD_SYNC_PATH 0x00000020u
#define ANTIVIRUS_REALTIME_REQUEST_FLAG_ADS_PATH 0x00000040u
#define ANTIVIRUS_REALTIME_REQUEST_FLAG_REPARSE_PATH 0x00000080u
#define ANTIVIRUS_REALTIME_REQUEST_FLAG_SECTION_MAP_EXECUTE 0x00000100u
#define ANTIVIRUS_REALTIME_REQUEST_FLAG_SECTION_MAP_WRITE 0x00000200u

#define ANTIVIRUS_REALTIME_PATH_RISK_HIGH_RISK_PATH 0x00000001u
#define ANTIVIRUS_REALTIME_PATH_RISK_USER_CONTROLLED 0x00000002u
#define ANTIVIRUS_REALTIME_PATH_RISK_EXECUTABLE_EXTENSION 0x00000004u
#define ANTIVIRUS_REALTIME_PATH_RISK_SCRIPT_EXTENSION 0x00000008u
#define ANTIVIRUS_REALTIME_PATH_RISK_CONTAINER_EXTENSION 0x00000010u
#define ANTIVIRUS_REALTIME_PATH_RISK_TRAVERSAL_SEQUENCE 0x00000020u
#define ANTIVIRUS_REALTIME_PATH_RISK_ADS_PATH 0x00000040u

#define ANTIVIRUS_REALTIME_SIGNER_TRUST_UNKNOWN 0u
#define ANTIVIRUS_REALTIME_SIGNER_TRUST_SYSTEM 1u
#define ANTIVIRUS_REALTIME_SIGNER_TRUST_PROGRAM_FILES 2u
#define ANTIVIRUS_REALTIME_SIGNER_TRUST_USER_PATH 3u

typedef struct ANTIVIRUS_REALTIME_SCAN_REQUEST {
  uint32_t protocolVersion;
  uint32_t requestSize;
  uint64_t requestId;
  uint32_t operation;
  uint32_t processId;
  uint32_t threadId;
  uint32_t parentProcessId;
  uint32_t desiredAccess;
  uint32_t createDisposition;
  uint32_t requestFlags;
  uint32_t signerTrustLevel;
  uint32_t pathRiskFlags;
  uint64_t fileSizeBytes;
  wchar_t correlationId[ANTIVIRUS_REALTIME_CORRELATION_CAPACITY];
  wchar_t path[ANTIVIRUS_REALTIME_PATH_CAPACITY];
  wchar_t processImage[ANTIVIRUS_REALTIME_IMAGE_CAPACITY];
  wchar_t commandLine[ANTIVIRUS_REALTIME_COMMAND_LINE_CAPACITY];
  wchar_t parentImage[ANTIVIRUS_REALTIME_IMAGE_CAPACITY];
  wchar_t userSid[ANTIVIRUS_REALTIME_USER_SID_CAPACITY];
} ANTIVIRUS_REALTIME_SCAN_REQUEST;

typedef struct ANTIVIRUS_REALTIME_SCAN_REPLY {
  uint32_t protocolVersion;
  uint32_t replySize;
  uint64_t requestId;
  uint32_t action;
  uint32_t disposition;
  uint32_t confidence;
  wchar_t tacticId[ANTIVIRUS_REALTIME_ATTACK_ID_CAPACITY];
  wchar_t techniqueId[ANTIVIRUS_REALTIME_ATTACK_ID_CAPACITY];
  wchar_t quarantineRecordId[ANTIVIRUS_REALTIME_CORRELATION_CAPACITY];
  wchar_t evidenceRecordId[ANTIVIRUS_REALTIME_CORRELATION_CAPACITY];
  wchar_t reasonCode[ANTIVIRUS_REALTIME_REASON_CODE_CAPACITY];
  wchar_t reasonMessage[ANTIVIRUS_REALTIME_REASON_MESSAGE_CAPACITY];
} ANTIVIRUS_REALTIME_SCAN_REPLY;

#pragma pack(pop)

#ifdef __cplusplus
}

namespace antivirus::agent {

using RealtimeFileScanRequest = ANTIVIRUS_REALTIME_SCAN_REQUEST;
using RealtimeFileScanReply = ANTIVIRUS_REALTIME_SCAN_REPLY;
using RealtimeFileOperation = ANTIVIRUS_REALTIME_FILE_OPERATION;
using RealtimeResponseAction = ANTIVIRUS_REALTIME_RESPONSE_ACTION;
using RealtimeResponseDisposition = ANTIVIRUS_REALTIME_RESPONSE_DISPOSITION;

inline constexpr wchar_t kRealtimeProtectionPortName[] = ANTIVIRUS_REALTIME_PORT_NAME;

}  // namespace antivirus::agent
#endif
