import type { ControlPlaneState } from "./types.ts";

export const DEMO_DEVICE_IDS = [
  "dev-lon-001",
  "dev-lon-002",
  "dev-lon-003",
  "dev-lon-004",
  "dev-lon-005",
  "dev-lon-006",
  "dev-lon-007",
  "dev-lon-008"
] as const;
export const DEMO_HOSTNAMES = [
  "FINANCE-LAPTOP-07",
  "OPS-DESKTOP-03",
  "HR-LAPTOP-12",
  "ENG-WORKSTATION-15",
  "SALES-LAPTOP-21",
  "EXEC-LAPTOP-02",
  "IT-JUMPBOX-01",
  "KIOSK-EDGE-04"
] as const;

function minusMinutes(baseIso: string, minutes: number) {
  return new Date(Date.parse(baseIso) - minutes * 60_000).toISOString();
}

function createDefaultPolicy() {
  return {
    id: "policy-default",
    name: "Business Baseline",
    revision: "2026.04.08.1",
    realtimeProtection: true,
    cloudLookup: true,
    scriptInspection: true,
    networkContainment: false,
    quarantineOnMalicious: true,
    dnsGuardEnabled: false,
    trafficTelemetryEnabled: true,
    integrityWatchEnabled: true,
    privilegeHardeningEnabled: true,
    pamLiteEnabled: true,
    denyHighRiskElevation: true,
    denyUnsignedElevation: true,
    requireBreakGlassEscrow: true
  };
}

function createDefaultPolicyProfile(baseIso: string) {
  return {
    ...createDefaultPolicy(),
    description: "Balanced endpoint baseline for always-on protection, script inspection, and analyst-led containment.",
    isDefault: true,
    assignedDeviceIds: [],
    createdAt: baseIso,
    updatedAt: baseIso
  };
}

export function createEmptyState(baseIso: string = new Date().toISOString()): ControlPlaneState {
  return {
    defaultPolicy: createDefaultPolicy(),
    policies: [createDefaultPolicyProfile(baseIso)],
    scripts: [],
    devices: [],
    alerts: [],
    telemetry: [],
    commands: [],
    quarantineItems: [],
    evidence: [],
    scanHistory: [],
    devicePosture: [],
    deviceRiskTelemetry: [],
    deviceScoreHistory: [],
    privilegeBaselines: [],
    privilegeEvents: [],
    privilegeStates: []
  };
}

export function createSeedState(baseIso: string = new Date().toISOString()): ControlPlaneState {
  const defaultPolicy = createDefaultPolicy();
  const financeSoftware = [
    {
      id: "sw-fin-vpn",
      displayName: "Contoso VPN",
      displayVersion: "5.4.2",
      publisher: "Contoso",
      installLocation: "C:\\Program Files\\Contoso\\VPN",
      uninstallCommand: "MsiExec.exe /x {CONTOSO-VPN-001} /qn",
      quietUninstallCommand: "MsiExec.exe /x {CONTOSO-VPN-001} /qn",
      installDate: "2026-03-12",
      displayIconPath: "C:\\Program Files\\Contoso\\VPN\\vpn.exe",
      executableNames: ["vpn.exe"],
      blocked: false,
      updateState: "available" as const,
      lastUpdateCheckAt: minusMinutes(baseIso, 11),
      updateSummary: "Version 5.5.0 is available from the configured software catalog."
    },
    {
      id: "sw-fin-reader",
      displayName: "Adobe Acrobat Reader",
      displayVersion: "24.001.1000",
      publisher: "Adobe",
      installLocation: "C:\\Program Files\\Adobe\\Acrobat Reader",
      uninstallCommand: "\"C:\\Program Files\\Adobe\\Acrobat Reader\\Setup.exe\" /remove /quiet",
      executableNames: ["acrord32.exe"],
      blocked: false,
      updateState: "current" as const,
      lastUpdateCheckAt: minusMinutes(baseIso, 32),
      updateSummary: "No newer package was reported during the last update check."
    }
  ];
  const engineeringSoftware = [
    {
      id: "sw-eng-browser",
      displayName: "Google Chrome",
      displayVersion: "134.0.0.0",
      publisher: "Google",
      installLocation: "C:\\Program Files\\Google\\Chrome\\Application",
      executableNames: ["chrome.exe"],
      blocked: false,
      updateState: "available" as const,
      lastUpdateCheckAt: minusMinutes(baseIso, 45),
      updateSummary: "Version 135 is available."
    },
    {
      id: "sw-eng-remote",
      displayName: "PuTTY",
      displayVersion: "0.81",
      publisher: "PuTTY",
      installLocation: "C:\\Program Files\\PuTTY",
      executableNames: ["putty.exe"],
      blocked: false,
      updateState: "current" as const
    }
  ];
  const kioskSoftware = [
    {
      id: "sw-kiosk-edge",
      displayName: "Microsoft Edge",
      displayVersion: "135.0.0.0",
      publisher: "Microsoft",
      installLocation: "C:\\Program Files (x86)\\Microsoft\\Edge\\Application",
      executableNames: ["msedge.exe"],
      blocked: false,
      updateState: "current" as const
    }
  ];

  return {
    defaultPolicy,
    policies: [
      {
        ...defaultPolicy,
        description: "Balanced endpoint baseline for everyday protected workstations.",
        isDefault: true,
        assignedDeviceIds: ["dev-lon-001", "dev-lon-002", "dev-lon-004", "dev-lon-008"],
        createdAt: minusMinutes(baseIso, 120),
        updatedAt: minusMinutes(baseIso, 15)
      },
      {
        id: "policy-containment",
        name: "High Containment",
        revision: "2026.04.08.2",
        realtimeProtection: true,
        cloudLookup: true,
        scriptInspection: true,
        networkContainment: true,
        quarantineOnMalicious: true,
        dnsGuardEnabled: true,
        trafficTelemetryEnabled: true,
        integrityWatchEnabled: true,
        privilegeHardeningEnabled: true,
        pamLiteEnabled: true,
        denyHighRiskElevation: true,
        denyUnsignedElevation: true,
        requireBreakGlassEscrow: true,
        description: "Tighter network containment and aggressive quarantine for high-risk devices.",
        isDefault: false,
        assignedDeviceIds: ["dev-lon-003", "dev-lon-005", "dev-lon-006", "dev-lon-007"],
        createdAt: minusMinutes(baseIso, 75),
        updatedAt: minusMinutes(baseIso, 20)
      },
      {
        id: "policy-servers",
        name: "Server Exposure Control",
        revision: "2026.04.08.3",
        realtimeProtection: true,
        cloudLookup: true,
        scriptInspection: true,
        networkContainment: true,
        quarantineOnMalicious: true,
        dnsGuardEnabled: true,
        trafficTelemetryEnabled: true,
        integrityWatchEnabled: true,
        privilegeHardeningEnabled: true,
        pamLiteEnabled: false,
        denyHighRiskElevation: true,
        denyUnsignedElevation: true,
        requireBreakGlassEscrow: true,
        description: "Harder exposure controls and tighter admin-surface review for server-class endpoints.",
        isDefault: false,
        assignedDeviceIds: ["dev-lon-004"],
        createdAt: minusMinutes(baseIso, 60),
        updatedAt: minusMinutes(baseIso, 12)
      }
    ],
    scripts: [
      {
        id: "script-001",
        name: "Collect triage bundle",
        description: "Collect a quick triage package from common staging locations.",
        language: "powershell",
        content: "Get-ChildItem $env:TEMP -Force | Select-Object -First 25 | Out-String",
        createdAt: minusMinutes(baseIso, 65),
        updatedAt: minusMinutes(baseIso, 65)
      },
      {
        id: "script-002",
        name: "Disable exposed admin service",
        description: "Example remediation script for turning off a risky service until the owner can review it.",
        language: "powershell",
        content: "Stop-Service -Name RemoteRegistry -Force; Set-Service -Name RemoteRegistry -StartupType Disabled",
        createdAt: minusMinutes(baseIso, 30),
        updatedAt: minusMinutes(baseIso, 18)
      }
    ],
    devices: [
      {
        id: "dev-lon-001",
        hostname: "FINANCE-LAPTOP-07",
        osVersion: "Windows 11 24H2",
        agentVersion: "0.1.0-alpha",
        platformVersion: "platform-0.1.0",
        serialNumber: "FIN-0007",
        enrolledAt: minusMinutes(baseIso, 24),
        lastSeenAt: minusMinutes(baseIso, 3),
        lastPolicySyncAt: minusMinutes(baseIso, 4),
        lastTelemetryAt: null,
        healthState: "healthy",
        isolated: false,
        policyId: "policy-default",
        policyName: "Business Baseline",
        privateIpAddresses: ["10.44.7.23"],
        publicIpAddress: "203.0.113.19",
        lastLoggedOnUser: "CORP\\finance.user",
        installedSoftware: financeSoftware
      },
      {
        id: "dev-lon-002",
        hostname: "OPS-DESKTOP-03",
        osVersion: "Windows 11 24H2",
        agentVersion: "0.1.0-alpha",
        platformVersion: "platform-0.1.0",
        serialNumber: "OPS-0003",
        enrolledAt: minusMinutes(baseIso, 42),
        lastSeenAt: minusMinutes(baseIso, 6),
        lastPolicySyncAt: minusMinutes(baseIso, 10),
        lastTelemetryAt: null,
        healthState: "degraded",
        isolated: false,
        policyId: "policy-default",
        policyName: "Business Baseline",
        privateIpAddresses: ["10.44.7.38", "192.168.56.1"],
        publicIpAddress: "203.0.113.44",
        lastLoggedOnUser: "CORP\\ops.user",
        installedSoftware: [
          {
            id: "sw-ops-remote",
            displayName: "RustDesk",
            displayVersion: "1.3.8",
            publisher: "RustDesk",
            installLocation: "C:\\Program Files\\RustDesk",
            uninstallCommand: "\"C:\\Program Files\\RustDesk\\uninstall.exe\" /S",
            executableNames: ["rustdesk.exe"],
            blocked: false,
            updateState: "available" as const,
            lastUpdateCheckAt: minusMinutes(baseIso, 18),
            updateSummary: "RustDesk 1.3.9 is available."
          },
          {
            id: "sw-ops-shell",
            displayName: "Unknown Remote Shell",
            displayVersion: "1.0",
            publisher: "unknown",
            installLocation: "C:\\Users\\ops.user\\AppData\\Local\\RemoteShell",
            executableNames: ["remoteshell.exe"],
            blocked: false,
            updateState: "error" as const,
            updateSummary: "Catalog lookup failed for this unsigned application."
          }
        ]
      },
      {
        id: "dev-lon-003",
        hostname: "HR-LAPTOP-12",
        osVersion: "Windows 10 22H2",
        agentVersion: "0.1.0-alpha",
        platformVersion: "platform-0.1.0",
        serialNumber: "HR-0012",
        enrolledAt: minusMinutes(baseIso, 61),
        lastSeenAt: minusMinutes(baseIso, 12),
        lastPolicySyncAt: minusMinutes(baseIso, 27),
        lastTelemetryAt: null,
        healthState: "isolated",
        isolated: true,
        policyId: "policy-containment",
        policyName: "High Containment",
        privateIpAddresses: ["10.44.8.16"],
        publicIpAddress: "198.51.100.17",
        lastLoggedOnUser: "CORP\\hr.user",
        installedSoftware: [
          {
            id: "sw-hr-chat",
            displayName: "Northwind Chat",
            displayVersion: "2.1.0",
            publisher: "Northwind",
            installLocation: "C:\\Program Files\\Northwind\\Chat",
            uninstallCommand: "\"C:\\Program Files\\Northwind\\Chat\\uninstall.exe\" /quiet",
            executableNames: ["northwind-chat.exe"],
            blocked: true,
            updateState: "error",
            lastUpdateCheckAt: minusMinutes(baseIso, 5),
            updateSummary: "Software is blocked pending review."
          }
        ]
      },
      {
        id: "dev-lon-004",
        hostname: "ENG-WORKSTATION-15",
        osVersion: "Windows 11 24H2",
        agentVersion: "0.1.0-alpha",
        platformVersion: "platform-0.1.0",
        serialNumber: "ENG-0015",
        enrolledAt: minusMinutes(baseIso, 55),
        lastSeenAt: minusMinutes(baseIso, 7),
        lastPolicySyncAt: minusMinutes(baseIso, 11),
        lastTelemetryAt: minusMinutes(baseIso, 9),
        healthState: "degraded",
        isolated: false,
        policyId: "policy-servers",
        policyName: "Server Exposure Control",
        privateIpAddresses: ["10.44.11.15"],
        publicIpAddress: "198.51.100.81",
        lastLoggedOnUser: "CORP\\eng.user",
        installedSoftware: engineeringSoftware
      },
      {
        id: "dev-lon-005",
        hostname: "SALES-LAPTOP-21",
        osVersion: "Windows 11 23H2",
        agentVersion: "0.1.0-alpha",
        platformVersion: "platform-0.1.0",
        serialNumber: "SLS-0021",
        enrolledAt: minusMinutes(baseIso, 74),
        lastSeenAt: minusMinutes(baseIso, 2),
        lastPolicySyncAt: minusMinutes(baseIso, 5),
        lastTelemetryAt: minusMinutes(baseIso, 2),
        healthState: "isolated",
        isolated: true,
        policyId: "policy-containment",
        policyName: "High Containment",
        privateIpAddresses: ["10.44.12.21"],
        publicIpAddress: "203.0.113.101",
        lastLoggedOnUser: "CORP\\sales.user",
        installedSoftware: [
          {
            id: "sw-sales-archive",
            displayName: "7-Zip",
            displayVersion: "22.01",
            publisher: "Igor Pavlov",
            installLocation: "C:\\Program Files\\7-Zip",
            executableNames: ["7zFM.exe"],
            blocked: false,
            updateState: "available" as const,
            lastUpdateCheckAt: minusMinutes(baseIso, 14),
            updateSummary: "7-Zip 24.x is available."
          }
        ]
      },
      {
        id: "dev-lon-006",
        hostname: "EXEC-LAPTOP-02",
        osVersion: "Windows 11 24H2",
        agentVersion: "0.1.0-alpha",
        platformVersion: "platform-0.1.0",
        serialNumber: "EXE-0002",
        enrolledAt: minusMinutes(baseIso, 88),
        lastSeenAt: minusMinutes(baseIso, 4),
        lastPolicySyncAt: minusMinutes(baseIso, 6),
        lastTelemetryAt: minusMinutes(baseIso, 4),
        healthState: "degraded",
        isolated: false,
        policyId: "policy-containment",
        policyName: "High Containment",
        privateIpAddresses: ["10.44.14.2"],
        publicIpAddress: "203.0.113.121",
        lastLoggedOnUser: "CORP\\exec.user",
        installedSoftware: [
          {
            id: "sw-exec-browser",
            displayName: "Mozilla Firefox",
            displayVersion: "135.0",
            publisher: "Mozilla",
            installLocation: "C:\\Program Files\\Mozilla Firefox",
            executableNames: ["firefox.exe"],
            blocked: false,
            updateState: "current" as const
          }
        ]
      },
      {
        id: "dev-lon-007",
        hostname: "IT-JUMPBOX-01",
        osVersion: "Windows Server 2022",
        agentVersion: "0.1.0-alpha",
        platformVersion: "platform-0.1.0",
        serialNumber: "IT-0001",
        enrolledAt: minusMinutes(baseIso, 95),
        lastSeenAt: minusMinutes(baseIso, 8),
        lastPolicySyncAt: minusMinutes(baseIso, 13),
        lastTelemetryAt: minusMinutes(baseIso, 8),
        healthState: "degraded",
        isolated: false,
        policyId: "policy-containment",
        policyName: "High Containment",
        privateIpAddresses: ["10.44.20.10"],
        publicIpAddress: "198.51.100.200",
        lastLoggedOnUser: "CORP\\it.admin",
        installedSoftware: [
          {
            id: "sw-it-rdpman",
            displayName: "RDCMan",
            displayVersion: "2.9",
            publisher: "Microsoft",
            installLocation: "C:\\Program Files\\RDCMan",
            executableNames: ["rdcman.exe"],
            blocked: false,
            updateState: "current" as const
          }
        ]
      },
      {
        id: "dev-lon-008",
        hostname: "KIOSK-EDGE-04",
        osVersion: "Windows 11 24H2",
        agentVersion: "0.1.0-alpha",
        platformVersion: "platform-0.1.0",
        serialNumber: "KSK-0004",
        enrolledAt: minusMinutes(baseIso, 33),
        lastSeenAt: minusMinutes(baseIso, 9),
        lastPolicySyncAt: minusMinutes(baseIso, 9),
        lastTelemetryAt: null,
        healthState: "healthy",
        isolated: false,
        policyId: "policy-default",
        policyName: "Business Baseline",
        privateIpAddresses: ["10.44.30.4"],
        publicIpAddress: null,
        lastLoggedOnUser: "KIOSK\\public",
        installedSoftware: kioskSoftware
      }
    ],
    alerts: [
      {
        id: "alert-001",
        deviceId: "dev-lon-002",
        title: "Obfuscated PowerShell launcher blocked",
        severity: "critical",
        status: "new",
        hostname: "OPS-DESKTOP-03",
        detectedAt: minusMinutes(baseIso, 7),
        technique: "T1059.001",
        summary: "AMSI and behavior scoring identified a staged PowerShell launcher attempting to fetch a payload."
      },
      {
        id: "alert-002",
        deviceId: "dev-lon-003",
        title: "Persistent outbound beacon investigation",
        severity: "high",
        status: "triaged",
        hostname: "HR-LAPTOP-12",
        detectedAt: minusMinutes(baseIso, 20),
        technique: "T1071",
        summary: "Residual beaconing was observed after the initial containment action."
      },
      {
        id: "alert-003",
        deviceId: "dev-lon-005",
        title: "Ransomware behaviour observed",
        severity: "critical",
        status: "new",
        hostname: "SALES-LAPTOP-21",
        detectedAt: minusMinutes(baseIso, 3),
        technique: "T1486",
        summary: "Burst file rewrite and ransom note creation indicate encryption impact activity."
      },
      {
        id: "alert-004",
        deviceId: "dev-lon-006",
        title: "Likely command-and-control beacon",
        severity: "critical",
        status: "new",
        hostname: "EXEC-LAPTOP-02",
        detectedAt: minusMinutes(baseIso, 4),
        technique: "T1071",
        summary: "Outbound timing and destination pattern are consistent with C2 beaconing."
      },
      {
        id: "alert-005",
        deviceId: "dev-lon-007",
        title: "Internet-exposed administrative surface requires review",
        severity: "high",
        status: "new",
        hostname: "IT-JUMPBOX-01",
        detectedAt: minusMinutes(baseIso, 9),
        technique: "T1133",
        summary: "The jump box exposes remote administration services while critical fixes remain overdue."
      },
      {
        id: "alert-006",
        deviceId: "dev-lon-004",
        title: "RDP exposure detected on engineering workstation",
        severity: "medium",
        status: "new",
        hostname: "ENG-WORKSTATION-15",
        detectedAt: minusMinutes(baseIso, 15),
        technique: "T1021.001",
        summary: "Remote Desktop remains exposed on an internet-addressable engineering endpoint."
      }
    ],
    telemetry: [
      {
        eventId: "telemetry-001",
        deviceId: "dev-lon-006",
        hostname: "EXEC-LAPTOP-02",
        eventType: "network.domain.malicious",
        source: "wfp",
        summary: "Likely command-and-control beacon detected to a malicious domain.",
        occurredAt: minusMinutes(baseIso, 4),
        ingestedAt: minusMinutes(baseIso, 4),
        payloadJson: "{\"destinationHost\":\"beacon.evil.example\"}"
      },
      {
        eventId: "telemetry-002",
        deviceId: "dev-lon-007",
        hostname: "IT-JUMPBOX-01",
        eventType: "network.port.snapshot",
        source: "wfp",
        summary: "RDP exposed on 3389 and SMB exposed on 445.",
        occurredAt: minusMinutes(baseIso, 8),
        ingestedAt: minusMinutes(baseIso, 8),
        payloadJson: "{\"open_port_count\":6,\"risky_open_port_count\":2,\"internet_exposed_admin_service_count\":1}"
      },
      {
        eventId: "telemetry-003",
        deviceId: "dev-lon-005",
        hostname: "SALES-LAPTOP-21",
        eventType: "process.ransomware.behaviour",
        source: "amsi",
        summary: "Burst file encryption and HOW_TO_RESTORE ransom note behaviour were observed.",
        occurredAt: minusMinutes(baseIso, 3),
        ingestedAt: minusMinutes(baseIso, 3),
        payloadJson: "{\"techniqueId\":\"T1486\"}"
      }
    ],
    commands: [
      {
        id: "cmd-001",
        deviceId: "dev-lon-003",
        hostname: "HR-LAPTOP-12",
        type: "device.isolate",
        status: "completed",
        createdAt: minusMinutes(baseIso, 56),
        updatedAt: minusMinutes(baseIso, 55),
        issuedBy: "soc-tier2"
      },
      {
        id: "cmd-002",
        deviceId: "dev-lon-002",
        hostname: "OPS-DESKTOP-03",
        type: "scan.targeted",
        status: "pending",
        createdAt: minusMinutes(baseIso, 5),
        updatedAt: minusMinutes(baseIso, 5),
        issuedBy: "automated-triage",
        targetPath: "C:\\Users\\ops\\Downloads",
        payloadJson: "{\"reason\":\"triage\"}"
      },
      {
        id: "cmd-003",
        deviceId: "dev-lon-005",
        hostname: "SALES-LAPTOP-21",
        type: "device.isolate",
        status: "completed",
        createdAt: minusMinutes(baseIso, 4),
        updatedAt: minusMinutes(baseIso, 3),
        issuedBy: "ransomware-playbook"
      }
    ],
    quarantineItems: [
      {
        recordId: "qr-001",
        deviceId: "dev-lon-002",
        hostname: "OPS-DESKTOP-03",
        originalPath: "C:\\Users\\ops.user\\Downloads\\staged-launcher.ps1",
        quarantinedPath: "C:\\ProgramData\\FenrirAgent\\runtime\\quarantine\\qr-001.ps1.quarantine",
        sha256: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
        sizeBytes: 48256,
        capturedAt: minusMinutes(baseIso, 7),
        lastUpdatedAt: minusMinutes(baseIso, 7),
        evidenceRecordId: "ev-001",
        technique: "T1059.001",
        status: "quarantined"
      },
      {
        recordId: "qr-002",
        deviceId: "dev-lon-005",
        hostname: "SALES-LAPTOP-21",
        originalPath: "C:\\Users\\sales.user\\AppData\\Local\\Temp\\HOW_TO_RESTORE_FILES.txt",
        quarantinedPath: "C:\\ProgramData\\FenrirAgent\\runtime\\quarantine\\qr-002.txt.quarantine",
        sha256: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        sizeBytes: 2200,
        capturedAt: minusMinutes(baseIso, 3),
        lastUpdatedAt: minusMinutes(baseIso, 3),
        evidenceRecordId: "ev-002",
        technique: "T1486",
        status: "quarantined"
      }
    ],
    evidence: [
      {
        recordId: "ev-001",
        deviceId: "dev-lon-002",
        hostname: "OPS-DESKTOP-03",
        recordedAt: minusMinutes(baseIso, 7),
        source: "scannercli",
        subjectPath: "C:\\Users\\ops.user\\Downloads\\staged-launcher.ps1",
        sha256: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
        disposition: "quarantine",
        tacticId: "TA0002",
        techniqueId: "T1059.001",
        contentType: "powershell",
        reputation: "user-writable-unsigned",
        quarantineRecordId: "qr-001",
        summary: "Evidence captured for the blocked staged PowerShell launcher."
      },
      {
        recordId: "ev-002",
        deviceId: "dev-lon-005",
        hostname: "SALES-LAPTOP-21",
        recordedAt: minusMinutes(baseIso, 3),
        source: "endpoint-ui-full-scan",
        subjectPath: "C:\\Users\\sales.user\\AppData\\Local\\Temp\\HOW_TO_RESTORE_FILES.txt",
        sha256: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        disposition: "quarantine",
        tacticId: "TA0040",
        techniqueId: "T1486",
        contentType: "text",
        reputation: "ransom-note",
        quarantineRecordId: "qr-002",
        summary: "Evidence captured for the ransom note dropped during the encryption sequence."
      }
    ],
    scanHistory: [
      {
        eventId: "scan-seed-001",
        deviceId: "dev-lon-002",
        hostname: "OPS-DESKTOP-03",
        scannedAt: minusMinutes(baseIso, 7),
        source: "scannercli",
        subjectPath: "C:\\Users\\ops.user\\Downloads\\staged-launcher.ps1",
        sha256: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
        contentType: "powershell",
        reputation: "user-writable-unsigned",
        disposition: "block",
        confidence: 98,
        tacticId: "TA0002",
        techniqueId: "T1059.001",
        remediationStatus: "quarantined",
        evidenceRecordId: "ev-001",
        quarantineRecordId: "qr-001",
        summary: "On-demand scan blocked the staged PowerShell launcher."
      },
      {
        eventId: "scan-seed-002",
        deviceId: "dev-lon-005",
        hostname: "SALES-LAPTOP-21",
        scannedAt: minusMinutes(baseIso, 3),
        source: "endpoint-ui-full-scan",
        subjectPath: "C:\\Users\\sales.user\\AppData\\Local\\Temp\\HOW_TO_RESTORE_FILES.txt",
        sha256: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        contentType: "text",
        reputation: "ransom-note",
        disposition: "block",
        confidence: 99,
        tacticId: "TA0040",
        techniqueId: "T1486",
        remediationStatus: "quarantined",
        evidenceRecordId: "ev-002",
        quarantineRecordId: "qr-002",
        summary: "Full scan detected a ransom note artifact during active encryption behaviour."
      }
    ],
    devicePosture: [
      {
        deviceId: "dev-lon-001",
        hostname: "FINANCE-LAPTOP-07",
        updatedAt: minusMinutes(baseIso, 5),
        overallState: "ready",
        tamperProtectionState: "ready",
        tamperProtectionSummary: "Protected runtime paths and service hardening are configured.",
        wscState: "ready",
        wscSummary: "Windows Security Center coexistence data was collected.",
        etwState: "ready",
        etwSummary: "The ETW process sensor started a real-time kernel event session.",
        wfpState: "ready",
        wfpSummary: "The WFP isolation manager opened the filtering engine and subscribed to net events.",
        isolationState: "inactive",
        isolationSummary: "Host isolation is not currently active.",
        registryConfigured: true,
        runtimePathsProtected: true,
        uninstallProtectionEnabled: true,
        wscAvailable: true,
        providerHealth: "security_center_running"
      },
      {
        deviceId: "dev-lon-002",
        hostname: "OPS-DESKTOP-03",
        updatedAt: minusMinutes(baseIso, 6),
        overallState: "degraded",
        tamperProtectionState: "degraded",
        tamperProtectionSummary: "Tamper settings are partially configured but not fully enforced.",
        wscState: "ready",
        wscSummary: "Windows Security Center coexistence data was collected.",
        etwState: "ready",
        etwSummary: "The ETW process sensor started a real-time kernel event session.",
        wfpState: "ready",
        wfpSummary: "The WFP manager is collecting connection telemetry.",
        isolationState: "inactive",
        isolationSummary: "Host isolation is not active.",
        registryConfigured: true,
        runtimePathsProtected: true,
        uninstallProtectionEnabled: true,
        wscAvailable: true,
        providerHealth: "security_center_running"
      },
      {
        deviceId: "dev-lon-003",
        hostname: "HR-LAPTOP-12",
        updatedAt: minusMinutes(baseIso, 10),
        overallState: "failed",
        tamperProtectionState: "degraded",
        tamperProtectionSummary: "Tamper protection could not complete its latest hardening cycle.",
        wscState: "ready",
        wscSummary: "Windows Security Center coexistence data was collected.",
        etwState: "failed",
        etwSummary: "The ETW sensor could not start a real-time session.",
        wfpState: "degraded",
        wfpSummary: "Network isolation is available but running in degraded mode.",
        isolationState: "active",
        isolationSummary: "Host isolation remains active.",
        registryConfigured: true,
        runtimePathsProtected: true,
        uninstallProtectionEnabled: true,
        wscAvailable: true,
        providerHealth: "security_center_running"
      },
      {
        deviceId: "dev-lon-004",
        hostname: "ENG-WORKSTATION-15",
        updatedAt: minusMinutes(baseIso, 8),
        overallState: "degraded",
        tamperProtectionState: "ready",
        wscState: "ready",
        etwState: "ready",
        wfpState: "degraded",
        wfpSummary: "Firewall telemetry is running but the host firewall is partially disabled.",
        isolationState: "inactive",
        isolationSummary: "Host isolation is not active."
      },
      {
        deviceId: "dev-lon-005",
        hostname: "SALES-LAPTOP-21",
        updatedAt: minusMinutes(baseIso, 2),
        overallState: "failed",
        tamperProtectionState: "degraded",
        wscState: "degraded",
        etwState: "ready",
        wfpState: "ready",
        isolationState: "active",
        isolationSummary: "Ransomware response playbook isolated the host."
      },
      {
        deviceId: "dev-lon-006",
        hostname: "EXEC-LAPTOP-02",
        updatedAt: minusMinutes(baseIso, 4),
        overallState: "degraded",
        tamperProtectionState: "ready",
        wscState: "ready",
        etwState: "ready",
        wfpState: "ready",
        isolationState: "inactive",
        isolationSummary: "Host isolation is not active."
      },
      {
        deviceId: "dev-lon-007",
        hostname: "IT-JUMPBOX-01",
        updatedAt: minusMinutes(baseIso, 7),
        overallState: "degraded",
        tamperProtectionState: "ready",
        wscState: "ready",
        etwState: "ready",
        wfpState: "ready",
        isolationState: "inactive",
        isolationSummary: "Host isolation is not active."
      },
      {
        deviceId: "dev-lon-008",
        hostname: "KIOSK-EDGE-04",
        updatedAt: minusMinutes(baseIso, 9),
        overallState: "ready",
        tamperProtectionState: "ready",
        wscState: "ready",
        etwState: "unknown",
        wfpState: "unknown",
        isolationState: "inactive",
        isolationSummary: "Host isolation is not active."
      }
    ],
    deviceRiskTelemetry: [
      {
        deviceId: "dev-lon-001",
        hostname: "FINANCE-LAPTOP-07",
        updatedAt: minusMinutes(baseIso, 5),
        source: "seed",
        os_patch_age_days: 5,
        critical_patches_overdue_count: 0,
        high_patches_overdue_count: 1,
        known_exploited_vuln_count: 0,
        internet_exposed_unpatched_critical_count: 0,
        unsupported_software_count: 0,
        outdated_browser_count: 0,
        outdated_high_risk_app_count: 0,
        untrusted_or_unsigned_software_count: 0,
        active_malware_count: 0,
        quarantined_threat_count_7d: 0,
        persistent_threat_count: 0,
        ransomware_behaviour_flag: false,
        lateral_movement_indicator: false,
        open_port_count: 0,
        risky_open_port_count: 0,
        internet_exposed_admin_service_count: 0,
        smb_exposed_flag: false,
        rdp_exposed_flag: false,
        malicious_domain_contacts_7d: 0,
        suspicious_domain_contacts_7d: 0,
        c2_beacon_indicator: false,
        data_exfiltration_indicator: false,
        unusual_egress_indicator: false,
        edr_enabled: true,
        av_enabled: true,
        firewall_enabled: true,
        disk_encryption_enabled: true,
        tamper_protection_enabled: true,
        local_admin_users_count: 1,
        risky_signin_indicator: false,
        stolen_token_indicator: false,
        mfa_gap_indicator: false
      },
      {
        deviceId: "dev-lon-002",
        hostname: "OPS-DESKTOP-03",
        updatedAt: minusMinutes(baseIso, 6),
        source: "seed",
        os_patch_age_days: 24,
        critical_patches_overdue_count: 1,
        high_patches_overdue_count: 3,
        known_exploited_vuln_count: 0,
        internet_exposed_unpatched_critical_count: 0,
        unsupported_software_count: 0,
        outdated_browser_count: 1,
        outdated_high_risk_app_count: 2,
        untrusted_or_unsigned_software_count: 1,
        active_malware_count: 1,
        quarantined_threat_count_7d: 1,
        persistent_threat_count: 0,
        ransomware_behaviour_flag: false,
        lateral_movement_indicator: false,
        open_port_count: 2,
        risky_open_port_count: 0,
        internet_exposed_admin_service_count: 0,
        smb_exposed_flag: false,
        rdp_exposed_flag: false,
        malicious_domain_contacts_7d: 0,
        suspicious_domain_contacts_7d: 2,
        c2_beacon_indicator: false,
        data_exfiltration_indicator: false,
        unusual_egress_indicator: true,
        edr_enabled: true,
        av_enabled: true,
        firewall_enabled: true,
        disk_encryption_enabled: true,
        tamper_protection_enabled: false,
        local_admin_users_count: 2,
        risky_signin_indicator: false,
        stolen_token_indicator: false,
        mfa_gap_indicator: false,
        tacticIds: ["TA0002"],
        techniqueIds: ["T1059.001"]
      },
      {
        deviceId: "dev-lon-003",
        hostname: "HR-LAPTOP-12",
        updatedAt: minusMinutes(baseIso, 10),
        source: "seed",
        os_patch_age_days: 46,
        critical_patches_overdue_count: 2,
        high_patches_overdue_count: 5,
        known_exploited_vuln_count: 1,
        internet_exposed_unpatched_critical_count: 0,
        unsupported_software_count: 1,
        outdated_browser_count: 0,
        outdated_high_risk_app_count: 1,
        untrusted_or_unsigned_software_count: 0,
        active_malware_count: 1,
        quarantined_threat_count_7d: 2,
        persistent_threat_count: 1,
        ransomware_behaviour_flag: false,
        lateral_movement_indicator: false,
        open_port_count: 2,
        risky_open_port_count: 1,
        internet_exposed_admin_service_count: 0,
        smb_exposed_flag: false,
        rdp_exposed_flag: false,
        malicious_domain_contacts_7d: 1,
        suspicious_domain_contacts_7d: 3,
        c2_beacon_indicator: false,
        data_exfiltration_indicator: false,
        unusual_egress_indicator: true,
        edr_enabled: false,
        av_enabled: true,
        firewall_enabled: true,
        disk_encryption_enabled: false,
        tamper_protection_enabled: false,
        local_admin_users_count: 2,
        risky_signin_indicator: true,
        stolen_token_indicator: false,
        mfa_gap_indicator: true,
        tacticIds: ["TA0011"],
        techniqueIds: ["T1071"]
      },
      {
        deviceId: "dev-lon-004",
        hostname: "ENG-WORKSTATION-15",
        updatedAt: minusMinutes(baseIso, 8),
        source: "seed",
        os_patch_age_days: 12,
        critical_patches_overdue_count: 0,
        high_patches_overdue_count: 1,
        known_exploited_vuln_count: 0,
        internet_exposed_unpatched_critical_count: 0,
        unsupported_software_count: 0,
        outdated_browser_count: 1,
        outdated_high_risk_app_count: 0,
        untrusted_or_unsigned_software_count: 0,
        active_malware_count: 0,
        quarantined_threat_count_7d: 0,
        persistent_threat_count: 0,
        ransomware_behaviour_flag: false,
        lateral_movement_indicator: false,
        open_port_count: 4,
        risky_open_port_count: 1,
        internet_exposed_admin_service_count: 0,
        smb_exposed_flag: false,
        rdp_exposed_flag: true,
        malicious_domain_contacts_7d: 0,
        suspicious_domain_contacts_7d: 0,
        c2_beacon_indicator: false,
        data_exfiltration_indicator: false,
        unusual_egress_indicator: false,
        edr_enabled: true,
        av_enabled: true,
        firewall_enabled: false,
        disk_encryption_enabled: true,
        tamper_protection_enabled: true,
        local_admin_users_count: 1,
        risky_signin_indicator: false,
        stolen_token_indicator: false,
        mfa_gap_indicator: false,
        tacticIds: ["TA0008"],
        techniqueIds: ["T1021.001"]
      },
      {
        deviceId: "dev-lon-005",
        hostname: "SALES-LAPTOP-21",
        updatedAt: minusMinutes(baseIso, 2),
        source: "seed",
        os_patch_age_days: 31,
        critical_patches_overdue_count: 1,
        high_patches_overdue_count: 2,
        known_exploited_vuln_count: 0,
        internet_exposed_unpatched_critical_count: 0,
        unsupported_software_count: 0,
        outdated_browser_count: 0,
        outdated_high_risk_app_count: 1,
        untrusted_or_unsigned_software_count: 0,
        active_malware_count: 2,
        quarantined_threat_count_7d: 3,
        persistent_threat_count: 1,
        ransomware_behaviour_flag: true,
        lateral_movement_indicator: false,
        open_port_count: 1,
        risky_open_port_count: 0,
        internet_exposed_admin_service_count: 0,
        smb_exposed_flag: false,
        rdp_exposed_flag: false,
        malicious_domain_contacts_7d: 1,
        suspicious_domain_contacts_7d: 2,
        c2_beacon_indicator: false,
        data_exfiltration_indicator: false,
        unusual_egress_indicator: true,
        edr_enabled: true,
        av_enabled: true,
        firewall_enabled: true,
        disk_encryption_enabled: true,
        tamper_protection_enabled: false,
        local_admin_users_count: 2,
        risky_signin_indicator: false,
        stolen_token_indicator: false,
        mfa_gap_indicator: false,
        tacticIds: ["TA0040"],
        techniqueIds: ["T1486"]
      },
      {
        deviceId: "dev-lon-006",
        hostname: "EXEC-LAPTOP-02",
        updatedAt: minusMinutes(baseIso, 4),
        source: "seed",
        os_patch_age_days: 18,
        critical_patches_overdue_count: 0,
        high_patches_overdue_count: 1,
        known_exploited_vuln_count: 0,
        internet_exposed_unpatched_critical_count: 0,
        unsupported_software_count: 0,
        outdated_browser_count: 0,
        outdated_high_risk_app_count: 0,
        untrusted_or_unsigned_software_count: 0,
        active_malware_count: 1,
        quarantined_threat_count_7d: 0,
        persistent_threat_count: 1,
        ransomware_behaviour_flag: false,
        lateral_movement_indicator: false,
        open_port_count: 1,
        risky_open_port_count: 0,
        internet_exposed_admin_service_count: 0,
        smb_exposed_flag: false,
        rdp_exposed_flag: false,
        malicious_domain_contacts_7d: 2,
        suspicious_domain_contacts_7d: 5,
        c2_beacon_indicator: true,
        data_exfiltration_indicator: true,
        unusual_egress_indicator: true,
        edr_enabled: true,
        av_enabled: true,
        firewall_enabled: true,
        disk_encryption_enabled: true,
        tamper_protection_enabled: true,
        local_admin_users_count: 1,
        risky_signin_indicator: true,
        stolen_token_indicator: true,
        mfa_gap_indicator: false,
        tacticIds: ["TA0011", "TA0010"],
        techniqueIds: ["T1071", "T1041"]
      },
      {
        deviceId: "dev-lon-007",
        hostname: "IT-JUMPBOX-01",
        updatedAt: minusMinutes(baseIso, 7),
        source: "seed",
        os_patch_age_days: 72,
        critical_patches_overdue_count: 3,
        high_patches_overdue_count: 6,
        known_exploited_vuln_count: 2,
        internet_exposed_unpatched_critical_count: 1,
        unsupported_software_count: 0,
        outdated_browser_count: 0,
        outdated_high_risk_app_count: 0,
        untrusted_or_unsigned_software_count: 0,
        active_malware_count: 0,
        quarantined_threat_count_7d: 0,
        persistent_threat_count: 0,
        ransomware_behaviour_flag: false,
        lateral_movement_indicator: false,
        open_port_count: 6,
        risky_open_port_count: 2,
        internet_exposed_admin_service_count: 1,
        smb_exposed_flag: true,
        rdp_exposed_flag: true,
        malicious_domain_contacts_7d: 0,
        suspicious_domain_contacts_7d: 1,
        c2_beacon_indicator: false,
        data_exfiltration_indicator: false,
        unusual_egress_indicator: false,
        edr_enabled: true,
        av_enabled: true,
        firewall_enabled: true,
        disk_encryption_enabled: true,
        tamper_protection_enabled: true,
        local_admin_users_count: 3,
        risky_signin_indicator: false,
        stolen_token_indicator: false,
        mfa_gap_indicator: true
      },
      {
        deviceId: "dev-lon-008",
        hostname: "KIOSK-EDGE-04",
        updatedAt: minusMinutes(baseIso, 9),
        source: "seed",
        edr_enabled: true,
        av_enabled: true,
        firewall_enabled: true,
        tamper_protection_enabled: true,
        local_admin_users_count: 1
      }
    ],
    deviceScoreHistory: [],
    privilegeBaselines: [
      {
        deviceId: "dev-lon-001",
        hostname: "FINANCE-LAPTOP-07",
        capturedAt: minusMinutes(baseIso, 23),
        localUsers: [
          { name: "CORP\\finance.user", source: "domain", enabled: true, authorized: true },
          { name: "FINANCE-LAPTOP-07-breakglass", source: "local", enabled: true, authorized: true }
        ],
        localAdministrators: [
          { name: "CORP\\IT Admins", source: "domain", enabled: true, authorized: true },
          { name: "FINANCE-LAPTOP-07-breakglass", source: "local", enabled: true, authorized: true }
        ],
        domainLinkedAdminMemberships: [
          { name: "CORP\\finance.user", group: "Local Administrators", source: "domain" }
        ],
        breakGlassAccountName: "FINANCE-LAPTOP-07-breakglass",
        breakGlassAccountEnabled: true,
        recoveryCredentialEscrowed: true,
        recoveryCredentialLastRotatedAt: minusMinutes(baseIso, 23)
      },
      {
        deviceId: "dev-lon-004",
        hostname: "ENG-WORKSTATION-15",
        capturedAt: minusMinutes(baseIso, 56),
        localUsers: [
          { name: "CORP\\eng.user", source: "domain", enabled: true, authorized: true },
          { name: "ENG-WORKSTATION-15-breakglass", source: "local", enabled: true, authorized: true }
        ],
        localAdministrators: [
          { name: "CORP\\Privileged Access", source: "domain", enabled: true, authorized: true },
          { name: "ENG-WORKSTATION-15-breakglass", source: "local", enabled: true, authorized: true }
        ],
        domainLinkedAdminMemberships: [
          { name: "CORP\\eng.user", group: "Local Administrators", source: "domain" }
        ],
        breakGlassAccountName: "ENG-WORKSTATION-15-breakglass",
        breakGlassAccountEnabled: true,
        recoveryCredentialEscrowed: true,
        recoveryCredentialLastRotatedAt: minusMinutes(baseIso, 56)
      },
      {
        deviceId: "dev-lon-006",
        hostname: "EXEC-LAPTOP-02",
        capturedAt: minusMinutes(baseIso, 41),
        localUsers: [
          { name: "CORP\\exec.user", source: "domain", enabled: true, authorized: true },
          { name: "EXEC-LAPTOP-02-breakglass", source: "local", enabled: true, authorized: true }
        ],
        localAdministrators: [
          { name: "CORP\\Executive Access", source: "domain", enabled: true, authorized: true },
          { name: "EXEC-LAPTOP-02-breakglass", source: "local", enabled: true, authorized: true }
        ],
        domainLinkedAdminMemberships: [
          { name: "CORP\\exec.user", group: "Local Administrators", source: "domain" }
        ],
        breakGlassAccountName: "EXEC-LAPTOP-02-breakglass",
        breakGlassAccountEnabled: true,
        recoveryCredentialEscrowed: true,
        recoveryCredentialLastRotatedAt: minusMinutes(baseIso, 41)
      }
    ],
    privilegeEvents: [
      {
        id: "pe-001",
        deviceId: "dev-lon-004",
        hostname: "ENG-WORKSTATION-15",
        recordedAt: minusMinutes(baseIso, 54),
        kind: "hardening.applied",
        actor: "console",
        severity: "high",
        source: "control-plane",
        summary: "PAM-lite hardening applied; standing administrator access is now restricted through the recovery path.",
        subject: "ENG-WORKSTATION-15"
      },
      {
        id: "pe-002",
        deviceId: "dev-lon-006",
        hostname: "EXEC-LAPTOP-02",
        recordedAt: minusMinutes(baseIso, 19),
        kind: "breakglass.used",
        actor: "console",
        severity: "high",
        source: "control-plane",
        summary: "Break-glass access was used recently for emergency administration.",
        subject: "EXEC-LAPTOP-02"
      }
    ],
    privilegeStates: [
      {
        deviceId: "dev-lon-004",
        hostname: "ENG-WORKSTATION-15",
        updatedAt: minusMinutes(baseIso, 53),
        privilegeHardeningMode: "restricted",
        pamEnforcementEnabled: true,
        standingAdminPresentFlag: true,
        unapprovedAdminAccountCount: 0,
        adminGroupTamperIndicator: false,
        directAdminLogonAttemptCount_7d: 1,
        breakGlassAccountUsageIndicator: false,
        unauthorisedAdminReenableIndicator: false,
        recoveryPathExists: true,
        lastEnforcedAt: minusMinutes(baseIso, 54),
        summary: "Privileged access is restricted. Standing admin access remains present.",
        recommendedActions: [
          "Replace standing local admin access with just-in-time elevation.",
          "Review recent direct administrator logons and elevation requests."
        ]
      },
      {
        deviceId: "dev-lon-006",
        hostname: "EXEC-LAPTOP-02",
        updatedAt: minusMinutes(baseIso, 18),
        privilegeHardeningMode: "monitor_only",
        pamEnforcementEnabled: false,
        standingAdminPresentFlag: true,
        unapprovedAdminAccountCount: 0,
        adminGroupTamperIndicator: false,
        directAdminLogonAttemptCount_7d: 0,
        breakGlassAccountUsageIndicator: true,
        unauthorisedAdminReenableIndicator: false,
        recoveryPathExists: true,
        lastBreakGlassUsedAt: minusMinutes(baseIso, 19),
        summary: "PAM-lite monitoring only. Break-glass access was used recently.",
        recommendedActions: [
          "Rotate break-glass credentials after emergency use.",
          "Replace standing local admin access with just-in-time elevation."
        ]
      }
    ]
    
  };
}
